name: "Tests"

on: [pull_request]
jobs:
  tests:
    name: Unit & E2E
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
  
    - name: Start test stack
      env:
        DO_ACCESS_KEY: ${{ secrets.DO_ACCESS_KEY }}
        DO_SECRET: ${{ secrets.DO_SECRET }}
        LINODE_ACCESS_KEY: ${{ secrets.LINODE_ACCESS_KEY }}
        LINODE_SECRET: ${{ secrets.LINODE_SECRET }}
      run: |
        docker compose up -d
        sleep 1

    - name: Doctor
      run: |
        docker compose logs
        docker ps
        docker network ls
    
    - name: Unit Tests
      run: docker compose exec -T tests vendor/bin/phpunit --configuration phpunit.xml --debug --testsuite unit
      
    - name: E2E Tests
      run: docker compose exec -T tests vendor/bin/phpunit --configuration phpunit.xml --debug --testsuite e2e
